# Generated by Django 4.1.7 on 2023-03-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('published_date', models.DateField()),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
                ('change_1h', models.CharField(max_length=10)),
                ('change_24h', models.CharField(max_length=10)),
                ('change_7d', models.CharField(max_length=10)),
                ('market_cap', models.CharField(max_length=20)),
                ('volume_24h', models.CharField(max_length=30)),
                ('circulating_supply', models.CharField(max_length=20)),
            ],
        ),
    ]
